//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.local {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BConsulta", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    [System.SerializableAttribute()]
    public partial class BConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clinic.local.BMedico MedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clinic.local.BPaciente PacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clinic.local.BTipoConsulta TipoConsultaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodConsulta {
            get {
                return this.CodConsultaField;
            }
            set {
                if ((this.CodConsultaField.Equals(value) != true)) {
                    this.CodConsultaField = value;
                    this.RaisePropertyChanged("CodConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HorarioField, value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clinic.local.BMedico Medico {
            get {
                return this.MedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicoField, value) != true)) {
                    this.MedicoField = value;
                    this.RaisePropertyChanged("Medico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clinic.local.BPaciente Paciente {
            get {
                return this.PacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteField, value) != true)) {
                    this.PacienteField = value;
                    this.RaisePropertyChanged("Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clinic.local.BTipoConsulta TipoConsulta {
            get {
                return this.TipoConsultaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoConsultaField, value) != true)) {
                    this.TipoConsultaField = value;
                    this.RaisePropertyChanged("TipoConsulta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BMedico", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    [System.SerializableAttribute()]
    public partial class BMedico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clinic.local.BClinica ClinicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataInscricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clinic.local.BClinica Clinica {
            get {
                return this.ClinicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicaField, value) != true)) {
                    this.ClinicaField = value;
                    this.RaisePropertyChanged("Clinica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Crm {
            get {
                return this.CrmField;
            }
            set {
                if ((object.ReferenceEquals(this.CrmField, value) != true)) {
                    this.CrmField = value;
                    this.RaisePropertyChanged("Crm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataInscricao {
            get {
                return this.DataInscricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataInscricaoField, value) != true)) {
                    this.DataInscricaoField = value;
                    this.RaisePropertyChanged("DataInscricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUser {
            get {
                return this.NomeUserField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeUserField, value) != true)) {
                    this.NomeUserField = value;
                    this.RaisePropertyChanged("NomeUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenhaUser {
            get {
                return this.SenhaUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaUserField, value) != true)) {
                    this.SenhaUserField = value;
                    this.RaisePropertyChanged("SenhaUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uf {
            get {
                return this.UfField;
            }
            set {
                if ((object.ReferenceEquals(this.UfField, value) != true)) {
                    this.UfField = value;
                    this.RaisePropertyChanged("Uf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BPaciente", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    [System.SerializableAttribute()]
    public partial class BPaciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Clinic.local.BConvenio ConvenioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Clinic.local.BConvenio Convenio {
            get {
                return this.ConvenioField;
            }
            set {
                if ((object.ReferenceEquals(this.ConvenioField, value) != true)) {
                    this.ConvenioField = value;
                    this.RaisePropertyChanged("Convenio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BTipoConsulta", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    [System.SerializableAttribute()]
    public partial class BTipoConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodTipoConsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodTipoCons {
            get {
                return this.CodTipoConsField;
            }
            set {
                if ((this.CodTipoConsField.Equals(value) != true)) {
                    this.CodTipoConsField = value;
                    this.RaisePropertyChanged("CodTipoCons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BClinica", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    [System.SerializableAttribute()]
    public partial class BClinica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescEspecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cnpj {
            get {
                return this.CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpjField, value) != true)) {
                    this.CnpjField = value;
                    this.RaisePropertyChanged("Cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEspec {
            get {
                return this.DescEspecField;
            }
            set {
                if ((object.ReferenceEquals(this.DescEspecField, value) != true)) {
                    this.DescEspecField = value;
                    this.RaisePropertyChanged("DescEspec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uf {
            get {
                return this.UfField;
            }
            set {
                if ((object.ReferenceEquals(this.UfField, value) != true)) {
                    this.UfField = value;
                    this.RaisePropertyChanged("Uf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BConvenio", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    [System.SerializableAttribute()]
    public partial class BConvenio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cnpj {
            get {
                return this.CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpjField, value) != true)) {
                    this.CnpjField = value;
                    this.RaisePropertyChanged("Cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BAdministrador", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    [System.SerializableAttribute()]
    public partial class BAdministrador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="local.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertConsulta", ReplyAction="http://tempuri.org/IService1/insertConsultaResponse")]
        bool insertConsulta(Clinic.local.BConsulta bCos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertConsulta", ReplyAction="http://tempuri.org/IService1/insertConsultaResponse")]
        System.Threading.Tasks.Task<bool> insertConsultaAsync(Clinic.local.BConsulta bCos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/alterConsulta", ReplyAction="http://tempuri.org/IService1/alterConsultaResponse")]
        bool alterConsulta(Clinic.local.BConsulta bCos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/alterConsulta", ReplyAction="http://tempuri.org/IService1/alterConsultaResponse")]
        System.Threading.Tasks.Task<bool> alterConsultaAsync(Clinic.local.BConsulta bCos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteConsulta", ReplyAction="http://tempuri.org/IService1/deleteConsultaResponse")]
        void deleteConsulta(Clinic.local.BConsulta bCos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteConsulta", ReplyAction="http://tempuri.org/IService1/deleteConsultaResponse")]
        System.Threading.Tasks.Task deleteConsultaAsync(Clinic.local.BConsulta bCos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listAdministrador", ReplyAction="http://tempuri.org/IService1/listAdministradorResponse")]
        Clinic.local.BAdministrador[] listAdministrador(Clinic.local.BAdministrador bAdm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listAdministrador", ReplyAction="http://tempuri.org/IService1/listAdministradorResponse")]
        System.Threading.Tasks.Task<Clinic.local.BAdministrador[]> listAdministradorAsync(Clinic.local.BAdministrador bAdm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listConsulta", ReplyAction="http://tempuri.org/IService1/listConsultaResponse")]
        Clinic.local.BConsulta[] listConsulta(Clinic.local.BConsulta bCos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listConsulta", ReplyAction="http://tempuri.org/IService1/listConsultaResponse")]
        System.Threading.Tasks.Task<Clinic.local.BConsulta[]> listConsultaAsync(Clinic.local.BConsulta bCos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listPaciente", ReplyAction="http://tempuri.org/IService1/listPacienteResponse")]
        Clinic.local.BPaciente[] listPaciente(Clinic.local.BPaciente bPac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listPaciente", ReplyAction="http://tempuri.org/IService1/listPacienteResponse")]
        System.Threading.Tasks.Task<Clinic.local.BPaciente[]> listPacienteAsync(Clinic.local.BPaciente bPac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listMedico", ReplyAction="http://tempuri.org/IService1/listMedicoResponse")]
        Clinic.local.BMedico[] listMedico(Clinic.local.BMedico bMed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listMedico", ReplyAction="http://tempuri.org/IService1/listMedicoResponse")]
        System.Threading.Tasks.Task<Clinic.local.BMedico[]> listMedicoAsync(Clinic.local.BMedico bMed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listTipoConsulta", ReplyAction="http://tempuri.org/IService1/listTipoConsultaResponse")]
        Clinic.local.BTipoConsulta[] listTipoConsulta(Clinic.local.BTipoConsulta bTip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listTipoConsulta", ReplyAction="http://tempuri.org/IService1/listTipoConsultaResponse")]
        System.Threading.Tasks.Task<Clinic.local.BTipoConsulta[]> listTipoConsultaAsync(Clinic.local.BTipoConsulta bTip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Clinic.local.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Clinic.local.IService1>, Clinic.local.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool insertConsulta(Clinic.local.BConsulta bCos) {
            return base.Channel.insertConsulta(bCos);
        }
        
        public System.Threading.Tasks.Task<bool> insertConsultaAsync(Clinic.local.BConsulta bCos) {
            return base.Channel.insertConsultaAsync(bCos);
        }
        
        public bool alterConsulta(Clinic.local.BConsulta bCos) {
            return base.Channel.alterConsulta(bCos);
        }
        
        public System.Threading.Tasks.Task<bool> alterConsultaAsync(Clinic.local.BConsulta bCos) {
            return base.Channel.alterConsultaAsync(bCos);
        }
        
        public void deleteConsulta(Clinic.local.BConsulta bCos) {
            base.Channel.deleteConsulta(bCos);
        }
        
        public System.Threading.Tasks.Task deleteConsultaAsync(Clinic.local.BConsulta bCos) {
            return base.Channel.deleteConsultaAsync(bCos);
        }
        
        public Clinic.local.BAdministrador[] listAdministrador(Clinic.local.BAdministrador bAdm) {
            return base.Channel.listAdministrador(bAdm);
        }
        
        public System.Threading.Tasks.Task<Clinic.local.BAdministrador[]> listAdministradorAsync(Clinic.local.BAdministrador bAdm) {
            return base.Channel.listAdministradorAsync(bAdm);
        }
        
        public Clinic.local.BConsulta[] listConsulta(Clinic.local.BConsulta bCos) {
            return base.Channel.listConsulta(bCos);
        }
        
        public System.Threading.Tasks.Task<Clinic.local.BConsulta[]> listConsultaAsync(Clinic.local.BConsulta bCos) {
            return base.Channel.listConsultaAsync(bCos);
        }
        
        public Clinic.local.BPaciente[] listPaciente(Clinic.local.BPaciente bPac) {
            return base.Channel.listPaciente(bPac);
        }
        
        public System.Threading.Tasks.Task<Clinic.local.BPaciente[]> listPacienteAsync(Clinic.local.BPaciente bPac) {
            return base.Channel.listPacienteAsync(bPac);
        }
        
        public Clinic.local.BMedico[] listMedico(Clinic.local.BMedico bMed) {
            return base.Channel.listMedico(bMed);
        }
        
        public System.Threading.Tasks.Task<Clinic.local.BMedico[]> listMedicoAsync(Clinic.local.BMedico bMed) {
            return base.Channel.listMedicoAsync(bMed);
        }
        
        public Clinic.local.BTipoConsulta[] listTipoConsulta(Clinic.local.BTipoConsulta bTip) {
            return base.Channel.listTipoConsulta(bTip);
        }
        
        public System.Threading.Tasks.Task<Clinic.local.BTipoConsulta[]> listTipoConsultaAsync(Clinic.local.BTipoConsulta bTip) {
            return base.Channel.listTipoConsultaAsync(bTip);
        }
    }
}
