//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Clinic.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insertConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback alterConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listAdministradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback listConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback listMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listTipoConsultaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Clinic.Properties.Settings.Default.Clinic_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insertConsultaCompletedEventHandler insertConsultaCompleted;
        
        /// <remarks/>
        public event alterConsultaCompletedEventHandler alterConsultaCompleted;
        
        /// <remarks/>
        public event deleteConsultaCompletedEventHandler deleteConsultaCompleted;
        
        /// <remarks/>
        public event listAdministradorCompletedEventHandler listAdministradorCompleted;
        
        /// <remarks/>
        public event listConsultaCompletedEventHandler listConsultaCompleted;
        
        /// <remarks/>
        public event listPacienteCompletedEventHandler listPacienteCompleted;
        
        /// <remarks/>
        public event listMedicoCompletedEventHandler listMedicoCompleted;
        
        /// <remarks/>
        public event listTipoConsultaCompletedEventHandler listTipoConsultaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/insertConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BConsulta bCos, out bool insertConsultaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool insertConsultaResultSpecified) {
            object[] results = this.Invoke("insertConsulta", new object[] {
                        bCos});
            insertConsultaResult = ((bool)(results[0]));
            insertConsultaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void insertConsultaAsync(BConsulta bCos) {
            this.insertConsultaAsync(bCos, null);
        }
        
        /// <remarks/>
        public void insertConsultaAsync(BConsulta bCos, object userState) {
            if ((this.insertConsultaOperationCompleted == null)) {
                this.insertConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertConsultaOperationCompleted);
            }
            this.InvokeAsync("insertConsulta", new object[] {
                        bCos}, this.insertConsultaOperationCompleted, userState);
        }
        
        private void OninsertConsultaOperationCompleted(object arg) {
            if ((this.insertConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertConsultaCompleted(this, new insertConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/alterConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alterConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BConsulta bCos, out bool alterConsultaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool alterConsultaResultSpecified) {
            object[] results = this.Invoke("alterConsulta", new object[] {
                        bCos});
            alterConsultaResult = ((bool)(results[0]));
            alterConsultaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void alterConsultaAsync(BConsulta bCos) {
            this.alterConsultaAsync(bCos, null);
        }
        
        /// <remarks/>
        public void alterConsultaAsync(BConsulta bCos, object userState) {
            if ((this.alterConsultaOperationCompleted == null)) {
                this.alterConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalterConsultaOperationCompleted);
            }
            this.InvokeAsync("alterConsulta", new object[] {
                        bCos}, this.alterConsultaOperationCompleted, userState);
        }
        
        private void OnalterConsultaOperationCompleted(object arg) {
            if ((this.alterConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alterConsultaCompleted(this, new alterConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/deleteConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BConsulta bCos) {
            this.Invoke("deleteConsulta", new object[] {
                        bCos});
        }
        
        /// <remarks/>
        public void deleteConsultaAsync(BConsulta bCos) {
            this.deleteConsultaAsync(bCos, null);
        }
        
        /// <remarks/>
        public void deleteConsultaAsync(BConsulta bCos, object userState) {
            if ((this.deleteConsultaOperationCompleted == null)) {
                this.deleteConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteConsultaOperationCompleted);
            }
            this.InvokeAsync("deleteConsulta", new object[] {
                        bCos}, this.deleteConsultaOperationCompleted, userState);
        }
        
        private void OndeleteConsultaOperationCompleted(object arg) {
            if ((this.deleteConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteConsultaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listAdministrador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
        public BAdministrador[] listAdministrador([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BAdministrador bAdm) {
            object[] results = this.Invoke("listAdministrador", new object[] {
                        bAdm});
            return ((BAdministrador[])(results[0]));
        }
        
        /// <remarks/>
        public void listAdministradorAsync(BAdministrador bAdm) {
            this.listAdministradorAsync(bAdm, null);
        }
        
        /// <remarks/>
        public void listAdministradorAsync(BAdministrador bAdm, object userState) {
            if ((this.listAdministradorOperationCompleted == null)) {
                this.listAdministradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistAdministradorOperationCompleted);
            }
            this.InvokeAsync("listAdministrador", new object[] {
                        bAdm}, this.listAdministradorOperationCompleted, userState);
        }
        
        private void OnlistAdministradorOperationCompleted(object arg) {
            if ((this.listAdministradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listAdministradorCompleted(this, new listAdministradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
        public BConsulta[] listConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BConsulta bCos) {
            object[] results = this.Invoke("listConsulta", new object[] {
                        bCos});
            return ((BConsulta[])(results[0]));
        }
        
        /// <remarks/>
        public void listConsultaAsync(BConsulta bCos) {
            this.listConsultaAsync(bCos, null);
        }
        
        /// <remarks/>
        public void listConsultaAsync(BConsulta bCos, object userState) {
            if ((this.listConsultaOperationCompleted == null)) {
                this.listConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistConsultaOperationCompleted);
            }
            this.InvokeAsync("listConsulta", new object[] {
                        bCos}, this.listConsultaOperationCompleted, userState);
        }
        
        private void OnlistConsultaOperationCompleted(object arg) {
            if ((this.listConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listConsultaCompleted(this, new listConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
        public BPaciente[] listPaciente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BPaciente bPac) {
            object[] results = this.Invoke("listPaciente", new object[] {
                        bPac});
            return ((BPaciente[])(results[0]));
        }
        
        /// <remarks/>
        public void listPacienteAsync(BPaciente bPac) {
            this.listPacienteAsync(bPac, null);
        }
        
        /// <remarks/>
        public void listPacienteAsync(BPaciente bPac, object userState) {
            if ((this.listPacienteOperationCompleted == null)) {
                this.listPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistPacienteOperationCompleted);
            }
            this.InvokeAsync("listPaciente", new object[] {
                        bPac}, this.listPacienteOperationCompleted, userState);
        }
        
        private void OnlistPacienteOperationCompleted(object arg) {
            if ((this.listPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listPacienteCompleted(this, new listPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
        public BMedico[] listMedico([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BMedico bMed) {
            object[] results = this.Invoke("listMedico", new object[] {
                        bMed});
            return ((BMedico[])(results[0]));
        }
        
        /// <remarks/>
        public void listMedicoAsync(BMedico bMed) {
            this.listMedicoAsync(bMed, null);
        }
        
        /// <remarks/>
        public void listMedicoAsync(BMedico bMed, object userState) {
            if ((this.listMedicoOperationCompleted == null)) {
                this.listMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistMedicoOperationCompleted);
            }
            this.InvokeAsync("listMedico", new object[] {
                        bMed}, this.listMedicoOperationCompleted, userState);
        }
        
        private void OnlistMedicoOperationCompleted(object arg) {
            if ((this.listMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listMedicoCompleted(this, new listMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listTipoConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
        public BTipoConsulta[] listTipoConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BTipoConsulta bTip) {
            object[] results = this.Invoke("listTipoConsulta", new object[] {
                        bTip});
            return ((BTipoConsulta[])(results[0]));
        }
        
        /// <remarks/>
        public void listTipoConsultaAsync(BTipoConsulta bTip) {
            this.listTipoConsultaAsync(bTip, null);
        }
        
        /// <remarks/>
        public void listTipoConsultaAsync(BTipoConsulta bTip, object userState) {
            if ((this.listTipoConsultaOperationCompleted == null)) {
                this.listTipoConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistTipoConsultaOperationCompleted);
            }
            this.InvokeAsync("listTipoConsulta", new object[] {
                        bTip}, this.listTipoConsultaOperationCompleted, userState);
        }
        
        private void OnlistTipoConsultaOperationCompleted(object arg) {
            if ((this.listTipoConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listTipoConsultaCompleted(this, new listTipoConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    public partial class BConsulta {
        
        private int codConsultaField;
        
        private bool codConsultaFieldSpecified;
        
        private string dataField;
        
        private string horarioField;
        
        private BMedico medicoField;
        
        private BPaciente pacienteField;
        
        private BTipoConsulta tipoConsultaField;
        
        /// <remarks/>
        public int CodConsulta {
            get {
                return this.codConsultaField;
            }
            set {
                this.codConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodConsultaSpecified {
            get {
                return this.codConsultaFieldSpecified;
            }
            set {
                this.codConsultaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Horario {
            get {
                return this.horarioField;
            }
            set {
                this.horarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BMedico Medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BPaciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BTipoConsulta TipoConsulta {
            get {
                return this.tipoConsultaField;
            }
            set {
                this.tipoConsultaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    public partial class BMedico {
        
        private string bairroField;
        
        private string cidadeField;
        
        private BClinica clinicaField;
        
        private string cpfField;
        
        private string crmField;
        
        private string dataInscricaoField;
        
        private string enderecoField;
        
        private string nomeField;
        
        private string nomeUserField;
        
        private string senhaUserField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BClinica Clinica {
            get {
                return this.clinicaField;
            }
            set {
                this.clinicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Crm {
            get {
                return this.crmField;
            }
            set {
                this.crmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataInscricao {
            get {
                return this.dataInscricaoField;
            }
            set {
                this.dataInscricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NomeUser {
            get {
                return this.nomeUserField;
            }
            set {
                this.nomeUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SenhaUser {
            get {
                return this.senhaUserField;
            }
            set {
                this.senhaUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    public partial class BClinica {
        
        private string bairroField;
        
        private string cidadeField;
        
        private string cnpjField;
        
        private string descEspecField;
        
        private string emailField;
        
        private string enderecoField;
        
        private string nomeField;
        
        private string telefoneField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescEspec {
            get {
                return this.descEspecField;
            }
            set {
                this.descEspecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    public partial class BAdministrador {
        
        private string cpfField;
        
        private string nomeField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    public partial class BTipoConsulta {
        
        private int codTipoConsField;
        
        private bool codTipoConsFieldSpecified;
        
        private string descricaoField;
        
        private string nomeField;
        
        /// <remarks/>
        public int CodTipoCons {
            get {
                return this.codTipoConsField;
            }
            set {
                this.codTipoConsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodTipoConsSpecified {
            get {
                return this.codTipoConsFieldSpecified;
            }
            set {
                this.codTipoConsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    public partial class BConvenio {
        
        private string bairroField;
        
        private string cidadeField;
        
        private string cnpjField;
        
        private string dataField;
        
        private string descricaoField;
        
        private string emailField;
        
        private string enderecoField;
        
        private string horaField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.model.basic")]
    public partial class BPaciente {
        
        private string bairroField;
        
        private BConvenio convenioField;
        
        private string cpfField;
        
        private string dataField;
        
        private string emailField;
        
        private string enderecoField;
        
        private string horaField;
        
        private string nomeField;
        
        private string telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BConvenio Convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void insertConsultaCompletedEventHandler(object sender, insertConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool insertConsultaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool insertConsultaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void alterConsultaCompletedEventHandler(object sender, alterConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alterConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alterConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool alterConsultaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool alterConsultaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deleteConsultaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listAdministradorCompletedEventHandler(object sender, listAdministradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listAdministradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listAdministradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BAdministrador[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BAdministrador[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listConsultaCompletedEventHandler(object sender, listConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BConsulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BConsulta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listPacienteCompletedEventHandler(object sender, listPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BPaciente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BPaciente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listMedicoCompletedEventHandler(object sender, listMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BMedico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BMedico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void listTipoConsultaCompletedEventHandler(object sender, listTipoConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listTipoConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listTipoConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BTipoConsulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BTipoConsulta[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591